<?php
return [
    'pagination_number' => 3,
    /*all fields that the table parser will contain.*/
    'memberReport' => [
        'Transaction_date' => 'period',
        'Brand' => 'merchantname',
        'Tracker' => 'siteid',
        'Views' => 'impressions',
        'Clicks' => 'clicks',
        'FTDC' => 'firstdepositcount',
        'Active_Customers' => 'activeaccounts',
        'Depositing_Customers' => 'purchaccountcount',
        'Total_Deposits' => 'purchases',
        'NGR' => 'netrevenue',
        'Revenue_Share_Profit' => 'revsharecommission',
        'Total_Profit' => 'totalcommission',
    ],
    'net_refer' => [
        'Creative' => 'Media_ID',
        'Transaction_date' => 'Date',
        'Views' => 'Views',
        'Clicks' => 'Clicks',
        'Signups' => 'Signups',
        'FTDC' => 'First_Time_Depositing_Customers',
        'Depositing_Customers' => 'Depositing_Customers',
        'Active_Customers' => 'Active_Customers',
        'NGR' => 'Net_Revenue',
        'Revenue_Share_Profit' => 'Revenue_Share_Reward',
        'CPA_Profit' => 'CPA_Reward',
        'Total_Profit' => 'Reward Due',
    ],
    'detailed_activity' => [
        'Brand' => 'Channel',
        'Transaction_date' => 'Date',
        'Views' => 'Impressions',
        'Clicks' => 'Clicks',
        'Signups' => 'NRC',
        'FTDC' => 'NDC',
        'Total_Deposits' => 'Total_Deposits',
        'Sportsbook_NGR' => 'Sportsbook_Net_Rev',
        'Casino_NGR' => 'Casino_Net_Rev',
        'NGR' => 'Total_Net_Rev',
        'Revenue_Share_Profit' => 'Revenue_Share_Profit',
        'Total_Profit' => 'Income',
    ],
    'player_registrations' => [
        'merchantname',
        'siteid',
        'bannerid',
        'playerid',
        'thedate',
    ],
    'all_fields_for_partner' => [
        'Brand',
        'Tracker',
        'Creative',
        'Transaction_date',
        'Views',
        'Clicks',
        'Signups',
        'FTDC',
        'Depositing_Customers',
        'Total_Deposits',
        'Active_Customers',
        'Sportsbook_NGR',
        'Casino_NGR',
        'NGR',
        'CPA_Qualified',
        'Revenue_Share_Profit',
        'CPA_Profit',
        'Total_Profit',
    ]
];
